[phases.setup]
nixPkgs = ["php", "phpExtensions.pdo_mysql", "phpExtensions.mbstring", "phpExtensions.openssl"]

[phases.install]
commands = [
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[start]
cmd = "php artisan config:clear && php artisan config:cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT}"
